version: "3.8"
services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /path/to/your/project/files:/data  # Mount your project files to /data in the container
    environment:
      - STREAMLIT_SERVER_PORT=8501